apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-t0er
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-t0er
    app.kubernetes.io/part-of: cin4s-839-0065-app
  name: devfile-sample-t0er
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-t0er
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-t0er
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0065-tenant/cin4s-839-0065-app/devfile-sample-t0er@sha256:cad978a94e3cf5fff59d0d99f19b698b41feaa0100fd4b369aea21ba076f6100
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
